version: '3.8'
services:
  postgres:
    container_name: dev-db
    image: postgres:16.0-alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dbdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - magazine_network

networks: 
  magazine_network:
    driver: bridge

volumes:
  postgres_data:
  
  
