version: '3.8'
services:
  postgres:
    container_name: prod-db
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
        - "${DB_PORT}:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    networks:
        - magazine_network

networks:
  magazine_network:
    driver: bridge

volumes:
  postgres_data:
  
  
